"""empty message

Revision ID: edee1b9e5cfd
Revises: 771a09bc1307
Create Date: 2026-05-13 10:46:01.716306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edee1b9e5cfd'
down_revision: Union[str, Sequence[str], None] = '771a09bc1307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('pages', sa.Integer(), nullable=True))
    op.add_column('user_books', sa.Column('current_page', sa.Integer(), nullable=True))
    op.add_column('user_books', sa.Column('total_pages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_books', 'total_pages')
    op.drop_column('user_books', 'current_page')
    op.drop_column('books', 'pages')
    # ### end Alembic commands ###
